sudo: required
services:
        - docker


before_install:
        - docker build -t sshetty007/docker-react -f Dockerfile.dev .

script:
        - docker run sshetty007/docker-react npm run test -- --coverage
